### ISSUE TITLE
Accepting Pull Requests?

### ISSUE THREAD

**Issue by hayesall** [Birion/python-ffdl#14]
Hello @Birion,

I was thinking about something similar to this project recently, and found yours! Is this still something you're interested in developing, and if so are you looking for potential collaboration?

Best,
@batflyer

**Comment by Birion** [comment]
Hey @batflyer,

To be perfectly honest, I've mostly made this script for myself since no other program was working well enough (or at all), and it just kinda blobbed from there. That being said, I'm well aware that there's hundreds, if not dozens of fanfic sites with their own unique idiosyncrasies, so I'm all for turning this into something useful to others as well.

Mind you, though -- I'm at best a basher (I bash things together for as long as needed before they start working), not a real programmer, so there's probably problems-a-plenty lurking around. Also, not really sure I'm doing this whole git thing correctly, so any messes -- totally my fault.

**Comment by hayesall** [comment]
I tried a few things out last night, this is cool! I'll do some experimentation on my fork, if I come up with any major quality-of-life improvements I'll open a pull request in case my changes are useful.

Never sell yourself short, you made something cool here! Programming is something we all learn over a lifetime :smile: 

Thanks for the response!
